# Generated by Django 4.1 on 2022-08-12 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ('horario',), 'verbose_name': 'Mi Curso', 'verbose_name_plural': 'Mis Cursos'},
        ),
    ]
