# Generated by Django 4.1 on 2022-08-13 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_alter_cursos_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesores',
            name='nivel',
        ),
        migrations.AddField(
            model_name='profesores',
            name='cursos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_1.cursos'),
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes')], default='Lunes', max_length=20)),
                ('cursos', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_1.cursos')),
            ],
        ),
    ]
