# Generated by Django 4.1 on 2022-08-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_remove_profesores_nivel_profesores_cursos_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Juenves'), ('Viernes', 'Viernes')], default='Lunes', max_length=20),
        ),
        migrations.DeleteModel(
            name='Semana',
        ),
    ]
