# Generated by Django 4.1 on 2022-08-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_cursos_dia_delete_semana'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ('dia', 'horario', 'nivel'), 'verbose_name': 'Mi Curso', 'verbose_name_plural': 'Mis Cursos'},
        ),
        migrations.AlterField(
            model_name='cursos',
            name='dia',
            field=models.CharField(choices=[('1-Lunes', '1-Lunes'), ('2-Martes', '2-Martes'), ('3-Miércoles', '3-Miércoles'), ('4-Jueves', '4-Jueves'), ('5-Viernes', '5-Viernes')], default='Lunes', max_length=20),
        ),
    ]
