# Generated by Django 4.0.6 on 2022-08-17 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_alter_cursos_options_alter_cursos_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesores',
            name='cursos',
        ),
    ]
