# Generated by Django 4.1 on 2022-08-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_remove_profesores_cursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='dia',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='horario',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nivel',
            field=models.CharField(max_length=20),
        ),
    ]
